"""Tests for Verilog generator V3 (parameters + alignment)."""

import pytest

from topstitcher.core.data_model import (
    PortInfo, PortDirection, ModuleInfo, InstanceInfo,
    PortAssignment, ParamInfo,
)
from topstitcher.core.connection_engine import ConnectionEngine
from topstitcher.core.verilog_generator import VerilogGenerator


@pytest.fixture
def generator():
    return VerilogGenerator()


def build_test_design(module_name="top_module"):
    adder_mod = ModuleInfo(
        name="adder",
        ports=[
            PortInfo("clk", PortDirection.INPUT, 1, "0", "0"),
            PortInfo("rst_n", PortDirection.INPUT, 1, "0", "0"),
            PortInfo("a", PortDirection.INPUT, 8, "7", "0"),
            PortInfo("b", PortDirection.INPUT, 8, "7", "0"),
            PortInfo("sum", PortDirection.OUTPUT, 8, "7", "0"),
        ],
    )
    reg_mod = ModuleInfo(
        name="register",
        ports=[
            PortInfo("clk", PortDirection.INPUT, 1, "0", "0"),
            PortInfo("rst_n", PortDirection.INPUT, 1, "0", "0"),
            PortInfo("d", PortDirection.INPUT, 8, "7", "0"),
            PortInfo("q", PortDirection.OUTPUT, 8, "7", "0"),
        ],
    )
    adder = InstanceInfo.from_module(adder_mod, "u_adder")
    register = InstanceInfo.from_module(reg_mod, "u_register")
    engine = ConnectionEngine()
    global_sigs = ["clk", "rst_n"]
    assignments = engine.build_assignments(
        [adder, register], global_signals=global_sigs
    )
    return engine.resolve_design(
        module_name, [adder, register], assignments,
        global_signals=global_sigs,
    )


class TestOutputFormat:
    def test_has_timescale(self, generator):
        code = generator.generate(build_test_design())
        assert "`timescale 1ns / 1ps" in code

    def test_has_module_declaration(self, generator):
        code = generator.generate(build_test_design())
        assert "module top_module (" in code
        assert "endmodule" in code

    def test_has_header_comment(self, generator):
        code = generator.generate(build_test_design())
        assert "Auto-generated by TopStitcher" in code

    def test_custom_module_name(self, generator):
        code = generator.generate(build_test_design("my_chip"))
        assert "module my_chip (" in code


class TestPortDeclarations:
    def test_input_ports(self, generator):
        code = generator.generate(build_test_design())
        assert "input" in code
        assert "a" in code
        assert "b" in code
        assert "d" in code

    def test_output_ports(self, generator):
        code = generator.generate(build_test_design())
        assert "output" in code
        assert "sum" in code
        assert "q" in code

    def test_global_signals_are_top_ports(self, generator):
        code = generator.generate(build_test_design())
        # clk and rst_n should appear as top-level inputs
        assert "input" in code
        # They should be in the port list, not just in instances
        lines = code.split("\n")
        port_section = []
        in_port = False
        for line in lines:
            if "module " in line and "(" in line:
                in_port = True
            if in_port:
                port_section.append(line)
            if in_port and ");" in line:
                break
        port_text = "\n".join(port_section)
        assert "clk" in port_text
        assert "rst_n" in port_text


class TestWireDeclarations:
    def test_no_global_wires(self, generator):
        """With global signals, clk/rst_n should NOT be internal wires."""
        design = build_test_design()
        wire_names = {w.net_name for w in design.internal_wires}
        assert "clk" not in wire_names
        assert "rst_n" not in wire_names


class TestInstantiation:
    def test_instances_present(self, generator):
        code = generator.generate(build_test_design())
        assert "adder u_adder (" in code
        assert "register u_register (" in code

    def test_port_connections(self, generator):
        code = generator.generate(build_test_design())
        # Aligned format: .port_name(net_name)
        assert ".clk" in code and "(clk" in code
        assert ".rst_n" in code and "(rst_n" in code
        assert ".a" in code and "(a" in code
        assert ".sum" in code and "(sum" in code


class TestGenerateFromTable:
    def test_manual_net_override(self, generator):
        """Simulate user editing the Assigned Net column."""
        adder_mod = ModuleInfo(
            name="adder",
            ports=[
                PortInfo("clk", PortDirection.INPUT, 1, "0", "0"),
                PortInfo("a", PortDirection.INPUT, 8, "7", "0"),
                PortInfo("sum", PortDirection.OUTPUT, 8, "7", "0"),
            ],
        )
        reg_mod = ModuleInfo(
            name="register",
            ports=[
                PortInfo("clk", PortDirection.INPUT, 1, "0", "0"),
                PortInfo("d", PortDirection.INPUT, 8, "7", "0"),
                PortInfo("q", PortDirection.OUTPUT, 8, "7", "0"),
            ],
        )
        adder = InstanceInfo.from_module(adder_mod, "u_adder")
        register = InstanceInfo.from_module(reg_mod, "u_register")

        # Manually create assignments as if user edited the table:
        # Connect sum → d via shared net "sum_to_d"
        assignments = [
            PortAssignment("u_adder", "adder", "clk", PortDirection.INPUT, 1, "0", "0", "clk"),
            PortAssignment("u_adder", "adder", "a", PortDirection.INPUT, 8, "7", "0", "a"),
            PortAssignment("u_adder", "adder", "sum", PortDirection.OUTPUT, 8, "7", "0", "sum_to_d"),
            PortAssignment("u_register", "register", "clk", PortDirection.INPUT, 1, "0", "0", "clk"),
            PortAssignment("u_register", "register", "d", PortDirection.INPUT, 8, "7", "0", "sum_to_d"),
            PortAssignment("u_register", "register", "q", PortDirection.OUTPUT, 8, "7", "0", "q"),
        ]
        code = generator.generate_from_table(
            "my_top", [adder, register], assignments,
            global_signals=["clk"],
        )
        assert "module my_top (" in code
        assert ".sum" in code and "sum_to_d" in code
        assert ".d" in code and "sum_to_d" in code
        # sum_to_d connects two ports → should be internal wire
        assert "wire" in code and "sum_to_d" in code


class TestRoundTrip:
    def test_parseable_output(self, generator):
        code = generator.generate(build_test_design())
        from pyverilog.vparser.parser import VerilogParser
        parser = VerilogParser()
        ast = parser.parse(code, debug=0)
        source = list(ast.children())[0]
        modules = list(source.children())
        assert len(modules) == 1
        assert modules[0].name == "top_module"


class TestParameterGeneration:
    def test_param_block_generated(self, generator):
        mod = ModuleInfo(
            name="DB",
            ports=[PortInfo("clk", PortDirection.INPUT, 1, "0", "0")],
            params=[ParamInfo("C", "1"), ParamInfo("MAX", "1000")],
        )
        inst = InstanceInfo.from_module(mod, "u_DB")
        engine = ConnectionEngine()
        assignments = engine.build_assignments([inst], global_signals=["clk"])
        design = engine.resolve_design(
            "top", [inst], assignments, global_signals=["clk"]
        )
        code = generator.generate(design)
        assert "DB #(" in code
        assert ".C" in code and "1" in code
        assert ".MAX" in code and "1000" in code
        assert ") u_DB (" in code

    def test_no_param_block_when_empty(self, generator):
        code = generator.generate(build_test_design())
        # adder has no params → no #(
        assert "adder u_adder (" in code
        lines = code.split("\n")
        for line in lines:
            if "adder u_adder" in line:
                assert "#(" not in line
                break

    def test_edited_param_values(self, generator):
        mod = ModuleInfo(
            name="fifo",
            ports=[PortInfo("clk", PortDirection.INPUT, 1, "0", "0")],
            params=[ParamInfo("DEPTH", "8")],
        )
        inst = InstanceInfo.from_module(mod, "u_fifo")
        # Simulate user editing parameter value
        inst.params[0].value = "32"
        engine = ConnectionEngine()
        assignments = engine.build_assignments([inst], global_signals=["clk"])
        design = engine.resolve_design(
            "top", [inst], assignments, global_signals=["clk"]
        )
        code = generator.generate(design)
        assert ".DEPTH" in code and "32" in code
        assert "8" not in code.split(".DEPTH")[1].split(")")[0]


class TestAlignment:
    def test_port_names_aligned(self, generator):
        """Port names within an instance should be padded to same length."""
        code = generator.generate(build_test_design())
        # In adder instance, .clk and .rst_n should be padded
        lines = code.split("\n")
        inst_lines = []
        in_inst = False
        for line in lines:
            if "adder u_adder" in line:
                in_inst = True
            if in_inst and line.strip().startswith("."):
                inst_lines.append(line)
            if in_inst and ");" in line:
                break
        # All opening parens should be at the same column
        paren_cols = [line.index("(") for line in inst_lines if "(" in line]
        assert len(set(paren_cols)) == 1  # all aligned

    def test_net_names_aligned(self, generator):
        """Net names within an instance should be padded to same length."""
        code = generator.generate(build_test_design())
        lines = code.split("\n")
        inst_lines = []
        in_inst = False
        for line in lines:
            if "adder u_adder" in line:
                in_inst = True
            if in_inst and line.strip().startswith("."):
                inst_lines.append(line)
            if in_inst and ");" in line:
                break
        # All closing parens should be at the same column
        close_cols = [line.rindex(")") for line in inst_lines if ")" in line]
        assert len(set(close_cols)) == 1
