"""Verilog code generator (workspace-first)."""

from topstitcher.core.data_model import (
    PortDirection, Connection, PortAssignment,
    InstanceInfo, TopModuleDesign, DesignWorkspace,
)


class VerilogGenerator:
    """Generates synthesizable Verilog code for the top module."""

    def generate(self, design: TopModuleDesign) -> str:
        port_to_net = self._build_port_to_net_map(design)
        lines = []

        lines.append("`timescale 1ns / 1ps")
        lines.append("")
        lines.append("//------------------------------------------------------")
        lines.append(f"// Module: {design.module_name}")
        lines.append("// Auto-generated by TopStitcher")
        lines.append("//------------------------------------------------------")
        lines.append("")

        sorted_ports = self._sort_ports(design.top_ports)
        if sorted_ports:
            lines.append(f"module {design.module_name} (")
            max_dir_len = max(
                len(p.direction.value) if p.direction else 5
                for p in sorted_ports
            )
            max_range_len = max(
                (len(p.range_str) if p.range_str else 0) for p in sorted_ports
            )
            if max_range_len > 0:
                max_range_len += 1

            for i, port in enumerate(sorted_ports):
                dir_str = port.direction.value if port.direction else "input"
                range_str = port.range_str if port.range_str else ""
                dir_padded = dir_str.ljust(max_dir_len)
                range_padded = range_str.ljust(max_range_len) if max_range_len else ""
                comma = "," if i < len(sorted_ports) - 1 else ""
                lines.append(
                    f"    {dir_padded} {range_padded}{port.net_name}{comma}"
                )
            lines.append(");")
        else:
            lines.append(f"module {design.module_name} ();")
        lines.append("")

        if design.internal_wires:
            lines.append("// Internal wires")
            max_range_len = max(
                (len(w.range_str) + 1 if w.range_str else 0)
                for w in design.internal_wires
            )
            for wire in design.internal_wires:
                range_str = wire.range_str
                if range_str:
                    range_padded = f" {range_str}".ljust(max_range_len + 1)
                else:
                    range_padded = " " * (max_range_len + 1) if max_range_len else ""
                lines.append(f"wire{range_padded} {wire.net_name};")
            lines.append("")

        for inst in design.instances:
            lines.extend(self._format_instance(inst, port_to_net))

        lines.append("endmodule")
        lines.append("")
        return "\n".join(lines)

    def _format_instance(
        self, inst: InstanceInfo, port_to_net: dict[tuple[str, str], str]
    ) -> list[str]:
        lines = []
        lines.append(f"// {inst.module_name} instance")

        if inst.params:
            max_pname = max(len(p.name) for p in inst.params)
            max_pval = max(len(p.value) for p in inst.params)
            lines.append(f"{inst.module_name} #(")
            for i, param in enumerate(inst.params):
                pname = param.name.ljust(max_pname)
                pval = param.value.ljust(max_pval)
                comma = "," if i < len(inst.params) - 1 else ""
                lines.append(f"    .{pname}({pval}){comma}")
            lines.append(f") {inst.instance_name} (")
        else:
            lines.append(f"{inst.module_name} {inst.instance_name} (")

        if inst.ports:
            max_port_name = max(len(p.name) for p in inst.ports)
            net_list = []
            for port in inst.ports:
                net = port_to_net.get(
                    (inst.instance_name, port.name), f"{inst.instance_name}_{port.name}"
                )
                net_list.append(net)
            max_net_name = max(len(n) for n in net_list)

            for i, (port, net) in enumerate(zip(inst.ports, net_list)):
                pname = port.name.ljust(max_port_name)
                nname = net.ljust(max_net_name)
                comma = "," if i < len(inst.ports) - 1 else ""
                lines.append(f"    .{pname}({nname}){comma}")

        lines.append(");")
        lines.append("")
        return lines

    def generate_from_table(
        self,
        module_name: str,
        instances: list[InstanceInfo],
        assignments: list[PortAssignment],
        global_signals: list[str] | None = None,
        promoted_ports: set[tuple[str, str]] | None = None,
    ) -> str:
        from topstitcher.core.connection_engine import ConnectionEngine
        engine = ConnectionEngine()
        design = engine.resolve_design(module_name, instances, assignments)
        return self.generate(design)

    def generate_from_workspace(
        self,
        module_name: str,
        workspace: DesignWorkspace,
    ) -> str:
        from topstitcher.core.connection_engine import ConnectionEngine
        engine = ConnectionEngine()
        design = engine.resolve_design_from_workspace(workspace, module_name)
        return self.generate(design)

    def _build_port_to_net_map(
        self, design: TopModuleDesign
    ) -> dict[tuple[str, str], str]:
        mapping = {}
        for conn in design.internal_wires + design.top_ports:
            for cp in conn.connected_ports:
                mapping[(cp.instance_name, cp.port_name)] = conn.net_name
        return mapping

    def _sort_ports(self, ports: list[Connection]) -> list[Connection]:
        order = {
            PortDirection.INPUT: 0,
            PortDirection.OUTPUT: 1,
            PortDirection.INOUT: 2,
        }
        return sorted(
            ports, key=lambda p: (order.get(p.direction, 3), p.net_name)
        )
